[project]
name = "transparent-band-array"
authors = ["Your Name <your.email@example.com>"]
description = "A decentralized supply chain tracking and verification platform"
telemetry = false
requirements = []
[contracts.supply-chain-tracker]
path = "contracts/supply-chain-tracker.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
